### PR TITLE
[Android] Edit main.xml in nnstreamer-ssd-autocapture and add some resource files

### PR DESCRIPTION
**Pull request by Soyeong-k-1230**
Edit main.xml for AutoCapture main UI and add some resource files to make ImageButtons and a click event.

Signed-off-by: Soyeong Kim <soyeong.kim.95@gmail.com>

---

### CODE REVIEW

**Comment by park-sang-hyun** [comment]
LGTM

**Comment by macaron10** [comment]
LGTM!

**Comment by JeongYeonUk** [comment]
LGTM!!

**Review by zhoonit — APPROVED** [review]
Life pro tips: use multiple branches instead of develop branches so that you don't need to wait to work on dependent PR.
eg.
commit 1. Add utill function f() <---------------- branch name: Soyeong-k:feature/util/f(PR #450)
commit 2. Add function g() that uses f() <- branch name: Soyeong-k:feature/implement/g (PR #451...)

and once #450 is merged, 
```bash
git checkout feature/implement/g
git rebase upstream/master
```
In this way, you can stack up multiple commits without affecting existing PR.

**Comment by Soyeong-k-1230** [comment]
Thank you for the good tips for using git commit. I'll try this way next PR. Appreciated your advice!

**Pull request merged**
