### PR TITLE
[native] Add example_servo_tracking application

### PR DESCRIPTION
**Pull request by dreamfinder2019**
This application tracks face using two servo motors.
This requires PCA9685 and two servo motor and Additional 5V 2A/4A Power Adapter.
Currently, This application only supports ARM64 based SBCs. And this supports rtmp youtube streaming by add parameter.
You can check more details in example_servo_tracking directory and README.md

Signed-off-by: JANG JONG HA <jangjongha.sw@gmail.com>

### CODE REVIEW

**Review by cocony12 — APPROVED** [review]
LGTM

**Review by YongjoonSeo — APPROVED** [review]
NNStreamer has an advantage when using AI model on device.
In this perspective, this example can be a reference for those who want to use NNStreamer on device.

**Review by soo-ni — APPROVED** [review]
LGTM

**Review by myungjoo — APPROVED** [review]
LGTM

**Pull request merged**
