### PR TITLE
[native] Upload base code of face_detection_tflite and python port of object_detection_tflite

### PR DESCRIPTION
**Pull request by dreamfinder2019**
We are currently working on porting object_detection_tflite to python. At this moment, We have succeeded in reading data from the label files. More elements like bus control and registering callbacks will be implemented shortly.

### CODE REVIEW

**Comment by zhoonit** [comment]
Could you try making this PR one commit?

**Review by YongjoonSeo — COMMENTED** [review]
The base python file of face detection example looks good to me at this level,
but it seems that nnstreamer_example_object_detection_tflite.py would be better to be pushed at least after it works, that is if you run the file it should be able to show the video from camera (or default video)

**Comment by dreamfinder2019** [comment]
> The base python file of face detection example looks good to me at this level,
> but it seems that nnstreamer_example_object_detection_tflite.py would be better to be pushed at least after it works, that is if you run the file it should be able to show the video from camera (or default video)

To respond to @YongjoonSeo's point, I implemented the code for the callback function in object_detection_tflite.py and set the global variable DEBUG to True to return the detection result. The newly pushed code now provides video.

**Review by YongjoonSeo — APPROVED** [review]
I think 'xvimagesink' of the pipeline in face_detection python file should be replaced with 'ximagesink' since sometimes 'xvimagesink' didn't work on Ubuntu 16.04 environment.
But at this level, both of files look good to me in that these files lay the groundwork for the future development.

**Review by cocony12 — APPROVED** [review]
LGTM

**Review by soo-ni — APPROVED** [review]
LGTM

**Comment by yeseul4072** [comment]
LGTM

**Review by zhoonit — APPROVED** [review]

**Pull request merged**
