### PR TITLE
[native] Modify Readme of separated examples - GUI, rtmp

### PR DESCRIPTION
**Pull request by YongjoonSeo**
GUI(ezstreamer.py) and rtmp (nnstreamer_example_face_detection_rtmp.py) directories are separated.
Several features have been updated:

1) Object Masking function added and it worked simultaneously. At this time, Knife and Scissor masking are only available options.
2) Drawing Region of Interests feature added. You can choose whether draws region of interests in your video.
3) The eye masking function corresponds to the detect main streamer function, just like face masking.
4) The UI has been stabilized by applying Layout feature and padding options.
5) The logic of some of the source code has been simplified. Especially in the section on toggle options.
6) Two examples (ezstreamer.py, nnstreamer_example_face_detection_rtmp.py) are separated and each README.md has been rewritten.

### CODE REVIEW

**Review by soo-ni — APPROVED** [review]
LGTM

**Review by dreamfinder2019 — APPROVED** [review]
Separating GUI Application to dedicated folders seems good choice. Applying NNStreamer to GUI is much different than just playing rtmp. LGTM

**Comment by dreamfinder2019** [comment]
If this PR is merged, we will immediately send a Pull Request with a large number of updates soon.
As the folder structure changes, we need to put the newly changed contents in the new folder, so we will wait for a while until this PR is merged.

**Review by zhoonit — APPROVED** [review]
LGTM

**Pull request merged**
