### PR TITLE
[native] Add readme into example_face_detection_tflite

### PR DESCRIPTION
**Pull request by YongjoonSeo**
Add README.md to initialize project directory

Signed-off-by: YongjoonSeo <koreakkrea12@naver.com>

### CODE REVIEW

**Review by myungjoo — APPROVED** [review]
LGTM.
Need approvals from @nnstreamer/ssafy-1

**Review by cocony12 — APPROVED** [review]
좋아용

**Review by yeseul4072 — APPROVED** [review]
LGTM

**Review by soo-ni — APPROVED** [review]
LGTM!! 좋슴당!!

**Review by gichan-jang — APPROVED** [review]
Congratulations on the first merge of team 1.

**Pull request merged**
