### PR TITLE
[Template] update nnstreamer changes

### PR DESCRIPTION
**Pull request by jaeyun-jung**
NNStreamer tensor-filter properties are recently changed and updated.
Fix errors and apply the changes to sub-plgin template.

Signed-off-by: Jaeyun <jy1210.jung@samsung.com>

### CODE REVIEW

**Comment by giladnahor** [comment]
Amazing response time!
Thanks a lot, this is a very good indication why I should use nnstreamer ;)

**Comment by giladnahor** [comment]
@jaeyun-jung hi I've tried working with your fix and I get this error:
** (gst-launch-1.0:32624): CRITICAL **: 13:25:46.140: nnstreamer_subplugin of temp(/usr/local/lib/nnstreamer/filters/libnnstreamer_filter_temp.so) is broken. It does not call register_subplugin with its init function.

I had to compile nnstreaner repo to allow the example to compile this is the version I used:
From https://github.com/nnstreamer/nnstreamer
   f53e419b..b84702b1  master     -> origin/master

In addition I've installed nnstreamer-dev using apt-get.
Am I missing something?
Thanks!!

**Comment by jaeyun-jung** [comment]
@giladnahor please check `nnstreamer.ini` file (under /etc)
```
[filter]
filters=/usr/lib/nnstreamer/filters/
```

Default meson option 'prefix' is '/usr/local' (https://mesonbuild.com/Builtin-options.html)
If you didn't change the option when building the project, filter subplugin would be installed to /user/local.

change build configuration with prefix (e.g., `$ meson --prefix=/usr build`), then the filter sub-plugin would be registered.

**Comment by giladnahor** [comment]
> @giladnahor please check `nnstreamer.ini` file (under /etc)
> If you installed nnstreamer from ppa, filter subplugin path is /usr/lib/nnstreamer/filters.
> 
> ```
> [filter]
> filters=/usr/lib/nnstreamer/filters/
> ```
> 
> Default meson option 'prefix' is '/usr/local' (https://mesonbuild.com/Builtin-options.html)
> If you didn't change the option when building the project, filter subplugin would be installed to /usr/local.
> 
> change build configuration with prefix (e.g., `$ meson --prefix=/usr build`), then the filter sub-plugin would be registered.

That did the trick, thanks!

**Review by myungjoo — APPROVED** [review]

**Comment by myungjoo** [comment]
> @giladnahor please check `nnstreamer.ini` file (under /etc)
> If you installed nnstreamer from ppa, filter subplugin path is /usr/lib/nnstreamer/filters.
> 
> ```
> [filter]
> filters=/usr/lib/nnstreamer/filters/
> ```
> 
> Default meson option 'prefix' is '/usr/local' (https://mesonbuild.com/Builtin-options.html)
> If you didn't change the option when building the project, filter subplugin would be installed to /usr/local.
> 
> change build configuration with prefix (e.g., `$ meson --prefix=/usr build`), then the filter sub-plugin would be registered.

We have "nnstreamer-util" in https://github.com/nnstreamer/nnstreamer/tree/master/tools/development/confchk

This utility will show all related installation status.

**Pull request merged**
