### PR TITLE
[native] Modify ezstreamer example for face mosaic

### PR DESCRIPTION
**Pull request by soo-ni**
Modify ezstreamer.py file.
When faces are detected in video stream,
faces are pixelated instead of being surrounded by square.

Signed-off-by: soo-ni <ksb940925@gmail.com>

### CODE REVIEW

**Review by cocony12 — APPROVED** [review]
LGTM

**Review by dreamfinder2019 — APPROVED** [review]
It seems that the missing function came back in the process of creating an application using PyQT. LGTM.

**Comment by yeseul4072** [comment]
LGTM

**Review by gichan-jang — APPROVED** [review]
Good luck with the SOSCON presentation.

**Pull request merged**
