### PR TITLE
[Android] Add style transfer example using java api

### PR DESCRIPTION
**Pull request by Ofiun**
This is a very simple example to show how to use NNStreamer APIs and Android Camera API to utilize the style transfer model.

- Model1: magenta_arbitrary-image-stylization-v1-256_int8_prediction_1
- Model2: magenta_arbitrary-image-stylization-v1-256_int8_transfer_1

Signed-off-by: EJ Jung proej11741@gmail.com

__Self evaluation:__

1. Build test: [*]Passed [ ]Failed [ ]Skipped
1. Run test: [*]Passed [ ]Failed [ ]Skipped

### CODE REVIEW

**Comment by jaeyun-jung** [comment]
Can you remove unnecessary files?
IMO, yo dont need to upload files `local.properties`, `.settings`, `.classpath`, `.idea`.
Also, when using nnstreamer.aar, .java files under `src/main/java/org/nnsuite/nnstreamer` are unnecessary.

**Comment by Ofiun** [comment]
@jaeyun-jung  Sorry, I did not know you commented.. I will check what you commented and request again as a new PR.

**Comment by jaeyun-jung** [comment]
@Ofiun local.properties, .settings, .classpath, .idea 
These files would be generated when importing project in android-studio. (local setting on your pc)
Also, after copying NNStreamer API library into libs directory, java files in org/nnsuite/nnstreamer (e.g., NNStreamer.java, TensorsInfo.java, ...) are unecessary, it already included in NNStreamer API library.

**Comment by Ofiun** [comment]
@jaeyun-jung I'm not sure about the second part. So is it okay for me to just upload nnstreamer/sample/MainActivity.java without four java files in the same nnstreamer/ folder?

**Comment by jaeyun-jung** [comment]
in build.gradle
implementation fileTree(include: ['*.aar'], dir: 'libs')

This will import .aar file in libs directory (NNStreamer API library is there), so I think you can build and run this project only with MainActivity.java.

**Comment by Ofiun** [comment]
Thank you for your explanation!
I'll request a new one without them!

**Pull request closed without merging**
