### PR TITLE
[native] Apply ui changes, add new features, adjust pipelines for ezstreamer

### PR DESCRIPTION
**Pull request by dreamfinder2019**
The following additions and changes have been updated in EZStreamer.

1) Now EZStreamer can change overlay mode in real time.
However, in the case of changing the streaming mode, since the rtmp key is needed,
quit the streaming is required.
2) Increased the video frames for tensor_filter to 15fps.
3) Changed the pipeline for all filter elements to run at once.
4) A function to exclude masking for large faces detected within the screen has been added.
5) Minimized the number of print warning and error logs that can be occured by buffer drop and streaming.
6) As the above update is reflected, we've made some changes to the streaming controller UI function.

Signed-off-by: JANG JONG HA <jangjongha.sw@gmail.com>

### CODE REVIEW

**Review by soo-ni — APPROVED** [review]
EZStreamer increased the video frames is great for reducing video stutter and convenient for real-time streaming by changing pipeline at once.
With these features, EZStreamer seems to be a good native application for those who stream live.

**Review by YongjoonSeo — APPROVED** [review]
For users who use nnstreamer for the first time, this application can be a good starting point to get used to nnstreamer since it offers several examples like face detection, object detection and so on.
For those who are already used to nnstreamer, this application can be a good reference thanks to intuitive GUI and most importantly, the quality of the application isn't that degraded after optimization.
Look good to me, well done.

**Comment by yeseul4072** [comment]
EZStreamer seems to have become more usable by adding several features.

**Review by gichan-jang — APPROVED** [review]
LGTM
Please add a demo video to README.md like:  
https://github.com/nnstreamer/nnstreamer-example/tree/master/native/example_pose_estimation_tflite#screenshots

**Pull request merged**
