### PR TITLE
[Android] nnstreamer-ssd files copy to nnstreamer-ssd-autocapture

### PR DESCRIPTION
**Pull request by JeongYeonUk**
- Source File in nnstreamer-ssd copy to nnstreamer-ssd-autocapture
- this new module added to settings.gradle

Signed-off-by: JeongYeonUk <dusdnrl1@naver.com>

### CODE REVIEW

**Comment by park-sang-hyun** [comment]
This will be a good foundation for our project. LGTM!

**Comment by Joojihwan** [comment]
LGTM!

**Comment by macaron10** [comment]
I was looking forward to this source file, LGTM!

**Comment by Soyeong-k-1230** [comment]
LGTM!

**Review by anyj0527 — APPROVED** [review]
LGTM

**Pull request merged**
